export const configKeyTd = 'td'
const namespace = 'analytics-td'
export const debugNamespace = namespace+':debug'
export const errorNamespace = namespace+':error'
export const TYPE_EVENT = 'event'
export const TYPE_PAGEVIEW = 'pageview'